version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:2024.11.01
    steps:
      - checkout
      - run: node -v && npm -v
      - run: npm install
      - run: STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY JWT_SECRET=secret npm test

  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"

workflows:
  test-and-deploy-to-ec2:
    jobs:
      - test
      - deploy:
          requires:
            - test
